# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 861d92583b7817415e31f94e68cf792e56d8958446472d95734f30a4e8e9a0388c99617607986e838a08f0d2e29fc7b151c302b226f7337aafa703cfd6dd9747

test:
  secret_key_base: 37d3f51f876a4722aea6abb034fd401028cc03df749d7275cadd04bec1c66e6de251cea085052b240e4e68816b0a2de52ec048be8b1576364393aa690b82fa7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
